### ISSUE TITLE
Signup Page - Frontend design

### ISSUE THREAD

**Issue by obinnaakaolisa** [zuri-training/Team-dove#9]
- [x] Please confirm that the `navbar` and `footer` have been created, and the image resources exported into the public folder before you attempt this task.
- [x] Refer to the `Contributing.md` file before attempting the task.
- [x] In the `resources/views/auth` folder, create a `register.blade.php` file and do your coding with respect to the Figma design of the create account page.

Thanks!

**Comment by Deji98** [comment]
Okay, on it!
